### ISSUE TITLE
Thoughts on moving this to jsr.io?

### ISSUE THREAD

**Issue by justinmchase** [cloudydeno/deno-kubernetes_apis#8]
I've been using it, it works. It seems like jsr.io is denos long term plan for modules and it would be nice to see this get re-homed there from a maintenance perspective.

**Comment by danopia** [comment]
Sounds reasonable. I haven't familiarized myself with the publish process yet. I think jsr has scopes so I suppose I'd make a cloudydeno scope.

**Comment by justinmchase** [comment]
Yeah you need a scope and it has a similar feature where you can link it to your repo which grants you OIDC auth access from your workflows.

Here is an example of a super simple publish workflow I did in one of my repos:
https://github.com/justinmchase/type/blob/main/.github/workflows/publish.yml

**Comment by danopia** [comment]
I've registered a scope etc, but getting this particular module published will take a little longer. Complications include:

1. Can't import from https:// in JSR modules. I use several of my other modules and I'll likely be migrating those first:

    ![image](https://github.com/user-attachments/assets/0e093134-8b4f-4c39-b2ee-ec7885690943)

2. JSR requires listing all entrypoints for the package. I treat each Kubernetes API as its own entrypoint, so I'll have to update my generation pipeline to update the JSR entrypoint list as well.

**Comment by danopia** [comment]
I have published my first JSR package :) https://jsr.io/@cloudydeno/stream-observables

Will continue biting a chunk off every day or two. JSR has some new guidelines, even for stream-observables it made me update some of the files to pass the slowtypes check.

**Comment by danopia** [comment]
I now have `@cloudydeno/kubernetes-client` on JSR in parallel with `/x/`. (I don't intend to drop `/x/` for some time as I expect this module is imported in various scripts/libraries and don't want to suddenly gate updates behind switching those scripts to JSR imports)

The remaining work here in #13 is JSR's slow-types audit. In particular `all functions in the public API must have an explicit return type` gets flagged for all of my generated files. So I'll need to amend the codegen to put explicit return types. Especially on the structure validation functions like these: https://github.com/cloudydeno/deno-kubernetes_apis/blob/47558c3aebba17e217ce00615078d52673c7f539/lib/vpa/autoscaling.k8s.io%40v1/structs.ts#L65-L95

**Comment by danopia** [comment]
Importing from JSR should work now, e.g.:

```ts
import { autoDetectClient } from "jsr:@cloudydeno/kubernetes-client@0.7.3";
import { CoreV1Api } from "jsr:@cloudydeno/kubernetes-apis@0.5.1/core/v1";

const coreV1 = new CoreV1Api(await autoDetectClient());
const podList = await coreV1.namespace("nginx-internet").getPodList()
console.log(podList.items.map(x => x.metadata?.name));
```

Note that the module exports are a bit different. There's a slash between the apigroup and apiversion.
The jsr docs are actually kind of ok about this, once you pick an entrypoint anyway, e.g. https://jsr.io/@cloudydeno/kubernetes-apis@0.5.1/doc/networking.k8s.io/v1/~

Let me know if you have any issues using it

**Comment by justinmchase** [comment]
Very nice, I forgot to mention that the dependent modules sort of needed to be virally updated as well but I had the same experience updating some of my packages.
